;; kotoba-ui (liquid-glass) の静的 CSS を tauri/dist/vendor/ へ生成する（`bb ui-css`）。
;; liquid-glass-ui の Tier A/B CSS は css.core の EDN rule data から純関数で
;; 生成される（ビルドステップ不要・babashka-safe）。murakumo-studio は常時ダーク
;; テーマなので、Tier A は prefers-color-scheme に依存せず dark トークンで
;; :root を直接発行する（gftdcojp/manimani/scripts/gen_kotoba_ui_css.clj と同型）。
(require '[clojure.java.io :as io]
         '[liquid-glass.tokens :as t]
         '[liquid-glass.style :as s])

(def app-css
  "/* --- murakumo-studio app shell --- */
html{min-height:100%}
body{margin:0;min-height:100vh;color:#eef1f6;
  font-family:-apple-system,'Hiragino Sans',sans-serif;font-size:14px;line-height:1.5;
  background:radial-gradient(1200px 800px at 80% -10%,#243b5e 0%,rgba(36,59,94,0) 60%),
             radial-gradient(1000px 700px at -10% 30%,#1b3a4a 0%,rgba(27,58,74,0) 55%),
             radial-gradient(900px 900px at 50% 110%,#132c1f 0%,rgba(19,44,31,0) 55%),
             linear-gradient(160deg,#0b0d14 0%,#11131d 100%);
  background-attachment:fixed;overscroll-behavior:none;}
input,textarea,select{color:inherit}
.liquid-glass__text-field input::placeholder,
.liquid-glass__text-area textarea::placeholder{color:rgba(255,255,255,.45)}
.liquid-glass__menu-select select option{color:#1c1c1e}
.liquid-glass__tab-bar{width:100%}
.ms-chat-log{white-space:pre-wrap;overflow-wrap:anywhere}
.ms-model-row{display:flex;align-items:center;justify-content:space-between;gap:12px}
")

(def css
  (str "/* generated by scripts/gen_kotoba_ui_css.clj (`bb ui-css`) — 手編集禁止\n"
       "   tokens/style = kotoba-lang/liquid-glass-ui (via kotoba-lang/css EDN rules) */\n"
       (t/css-variables (t/resolve-dark-tokens nil))
       "\n"
       (s/component-css)
       "\n"
       app-css))

(let [out "tauri/dist/vendor/kotoba-ui.css"]
  (io/make-parents out)
  (spit out css)
  (println "✓" out (str "(" (count css) " bytes)")))
